run:
  go: "1.17"
  concurrency: 8
  deadline: 1m
  tests: false
  skip-dirs:
    - mocks
linters:
  enable:
    - deadcode
    - errcheck
    - goconst
    - gofmt
    - goimports
    - revive
    - ineffassign
    - misspell
    - structcheck
    - typecheck
    - unused
    - varcheck
    - vet
    - unparam
    - staticcheck
    - gosec
  enable-all: false
  disable-all: true